spring:
  application:
    name: security-oauth-jwt-asymmetric
  h2:
    console:
      enabled: true  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:sec
    username: sa
    password: 
    driver-class-name: org.h2.Driver    
logging:
  level:
    '[org.springframework.security]': trace
    
jwt:
  rsa-public-key: classpath:certs/testpublicKey.pem
  rsa-private-key: classpath:certs/testprivateKey.pem
  
access:
  token:
    expiry: 15*60
    issuer: applicationname  
  
  
#signin--u/p--server gives you token