spring:
  application:
    name: security-oauth-jwt-asymmetric
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:sec
    username: sa
    password: 
    driver-class-name: org.h2.Driver    
logging:
  level:
    '[org.springframework.security]': trace    
